apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: test-receiver
  namespace: flux-system
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: webhook-token
  resources:
    # - apiVersion: source.toolkit.fluxcd.io/v1
    #   kind: GitRepository
    #   name: "test-gitrepository"
    #   namespace: flux-system
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: "*"
      matchLabels:
        repository: flux-receiver-matchlabels-issue
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-gitrepository-1
  namespace: flux-system
  labels:
    repository: flux-receiver-matchlabels-issue
spec:
  # Yes our GitRepository actually looks like this
  ignore: |
    *
    !./flux-target-1
  interval: 5m
  ref:
    branch: master
  timeout: 20s
  url: https://github.com/devjoes/flux-receiver-matchlabels-issue
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-kustomization-1
  namespace: flux-system
spec:
  interval: 600s
  path: ./flux-target-1
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-gitrepository
  timeout: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-gitrepository-2
  namespace: flux-system
  labels:
    repository: flux-receiver-matchlabels-issue
spec:
  # Yes our GitRepository actually looks like this
  ignore: |
    *
    !./flux-target-2
  interval: 5m
  ref:
    branch: master
  timeout: 20s
  url: https://github.com/devjoes/flux-receiver-matchlabels-issue
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-kustomization-2
  namespace: flux-system
spec:
  interval: 600s
  path: ./flux-target-2
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-gitrepository-2
  timeout: 5m
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-gitrepository-3
  namespace: flux-system
  labels:
    repository: flux-receiver-matchlabels-issue
spec:
  # Yes our GitRepository actually looks like this
  ignore: |
    *
    !./flux-target-3
  interval: 5m
  ref:
    branch: master
  timeout: 20s
  url: https://github.com/devjoes/flux-receiver-matchlabels-issue
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-kustomization-3
  namespace: flux-system
spec:
  interval: 600s
  path: ./flux-target-3
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-gitrepository-3
  timeout: 5m
---

